name: Lighthouse Report

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Serve build locally
        run: |
          npx http-server ./build -p 8080 & \
          npx wait-on http://127.0.0.1:8080

      - name: Run Lighthouse
        id: lh
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: http://127.0.0.1:8080
          uploadArtifacts: false            # <— turn off internal upload
          temporaryPublicStorage: true      # public link printed in logs

      - name: Upload Lighthouse artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse_report           # <— safe artifact name
          path: |
            ./.lighthouseci/*.html
            ./.lighthouseci/*.json
            ./.lighthouseci/manifest.json
          if-no-files-found: warn
