# ==============================================================
# GitHub Actions workflow: "OWASP Lite"
# Tools:
#   - Gitleaks (OWASP A08) for hardcoded secrets
#   - Semgrep (OWASP A01–A10) for SAST
# ==============================================================

name: OWASP Lite (Semgrep + Gitleaks)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  gitleaks:
    name: Secrets scan (A08)
    runs-on: ubuntu-latest
    env:
      # REQUIRED for org repos using gitleaks-action@v2
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          # redact: masks matching secrets in logs
          # config: optional custom rules/allowlist file
          args: detect --source . --redact --config .gitleaks.toml

  semgrep:
    name: SAST OWASP Top 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use the maintained Semgrep action which emits SARIF for Code Scanning
      - name: Semgrep SAST (OWASP Top 10)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
          generateSarif: "1"

      - name: Upload Semgrep SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif